# Generated by Django 5.2.7 on 2025-10-25 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('date_of_birth', models.DateField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tracks.track')),
            ],
        ),
    ]
